randomanimelist = (
    "Tokyo Ghoul", "Fullmetal Alchemist", "Castlevania", "Kill La Kill",
    "Naruto ", "Haikyuu", " Sword Art Online", "Darling In The Franxx ",
    "Overlord ", ",One Punch Man", "Free", " Lucky Star", "Elden Lied",
    "Log Horizon", "Cardcaptor Sakura", "Bezerk",
    "Magi: The Labyrinth of Magic", "Hellsing: Ultimate",
    "The Pet Girl of Sakurasou", "Katekyō Hitman Reborn", "Yu Yu Hakusho",
    "Yona Of The Dawn", "Charlotte", "Seraph Of The End", "Akane Ga Kill",
    "When They Cry", "Hyouka", "Ghost In The Shell", "Kuroko No Basket",
    "Terror In Resonance", "Natsume Yuujinchou", "Pokémon", "Akira",
    "Mushishi", "Dragon Ball", "Another", "Spice And Wolf",
    "FlCL (Fooly Cooly)", "Samurai Champloo", "Monster", "Shinseki Yori",
    "The Seven Deadly Sins", "Baccano", "Bungou Stray Dogs",
    "Miss Kobayshi's Dragon Maid", "Sailor Moon", "K-On!",
    "Nichijou (My Ordinary Life)", "Blue Exorcist", "Love Live", "Anohana",
    "Inuyasha", "Wolf Children", "Howls Moving Castle", "Highschool DxD",
    "Shokugeki No Soma (Food Wars)", "Princess Mononoke", "Bakemonogatari",
    "Erased,Mirai Nikki", "Psycho-Pass", "Monogatari", "Durarara",
    "Death Parade", "Clannad", "Bleach", "Ouran High School Host Club",
    "Fate/Zero", "Soul Eater", "Toradora", "Mod Psycho 100", "Dragon Ball Z",
    "Noragami", "Konosuba", "Black Butler", "Angel Beats", "Hunter x Hunter",
    "Madoka Magica", "Neon Genesis Evangelion", "Yuri On Ice", "Re:Zero",
    "Spirited Away", "JoJos Bizarre Adventure", "Gurren Lagann", "Gintama",
    "Assassination Classroom", "Cowboy Bebop", "Fairytail", "No Game No Life",
    "Koe No Katachi (A Silent Voice)", "Code Geass", "Your Lie In April",
    "One Piece", "Steins:Gate", " Attack On Titan", " Death Note", "Your Name",
    "Boku No Hero Academia", "To LOVE Ru", "Freezing", "The Familiar of Zero",
    "Inu X Boku Secret Service", " Date A Live", "Goblin Slayer",
    "Demon Slayer", "The Misfit Of Demon King Academy",
    "How Not To Summon A Demon Lord", "Infinite Stratos", "Asteroid In Love",
    "Mameshiba", "Horimiya", "go study instead dumbass", "overwatch",
    "rascal does not dream of bunny girl senpai")


